server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: hystrixpayment8001
    prefer-ip-address: true

