server:
  port: 9527


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: gateway9527
    prefer-ip-address: true

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的id,没有固定规则但要求唯一,建议配合服务名
#          uri: http://localhost:8001 #配置后提供服务的路由地址
          uri: lb://spring-cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route
#          uri: http://localhost:8001
          uri: lb://spring-cloud-payment-service #匹配后提供服务的路由地址
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤工厂会在匹配的请求头上加一队请求头，名称为x-Request-Id值为1024
          predicates:
            - Path=/payment/lb/** #断言，路径
#            - After=2022-12-19T18:03:49.717976+08:00[Asia/Shanghai]
#            - Cookie=username,piao
#            - Header=X-Request-Id, \d+