server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务器实例名称
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  #Eureka服务注册的地址
    register-with-eureka: false  #不向服务注册中心注册自己
    fetch-registry: false  #不需要去检索服务
#  server:
#    enable-self-preservation: false #eureka自我保护模式的开关
#    eviction-interval-timer-in-ms: 2000 #2000ms没有收到服务提供者的心跳，eureka将其除名
